use std::ffi::c_void;
use std::fmt;

use bitflags::bitflags;
use pkcs11_sys::*;

pub trait Mechanism {
    fn r#type(&self) -> MechanismType;
    fn as_ptr(&self) -> *const c_void;
    fn len(&self) -> CK_ULONG;
}

bitflags! {
    /// Bit flags specifying mechanism capabilities.
    pub struct MechanismFlags: CK_FLAGS {
        const HW = CKF_HW as CK_FLAGS;
        const ENCRYPT = CKF_ENCRYPT as CK_FLAGS;
        const DECRYPT = CKF_DECRYPT as CK_FLAGS;
        const DIGEST = CKF_DIGEST as CK_FLAGS;
        const SIGN = CKF_SIGN as CK_FLAGS;
        const SIGN_RECOVER = CKF_SIGN_RECOVER as CK_FLAGS;
        const VERIFY = CKF_VERIFY as CK_FLAGS;
        const VERIFY_RECOVER = CKF_VERIFY_RECOVER as CK_FLAGS;
        const GENERATE = CKF_GENERATE as CK_FLAGS;
        const GENERATE_KEY_PAIR = CKF_GENERATE_KEY_PAIR as CK_FLAGS;
        const WRAP = CKF_WRAP as CK_FLAGS;
        const UNWRAP = CKF_UNWRAP as CK_FLAGS;
        const DERIVE = CKF_DERIVE as CK_FLAGS;
        const EXTENSION = CKF_EXTENSION as CK_FLAGS;
    }
}

pub struct MechanismInfo {
    pub(crate) inner: CK_MECHANISM_INFO,
}

impl MechanismInfo {
    pub fn min_key_size(&self) -> CK_ULONG {
        self.inner.ulMinKeySize
    }

    pub fn max_key_size(&self) -> CK_ULONG {
        self.inner.ulMaxKeySize
    }

    pub fn flags(&self) -> MechanismFlags {
        MechanismFlags::from_bits_truncate(self.inner.flags)
    }
}

impl fmt::Debug for MechanismInfo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut d = f.debug_struct("MechanismInfo");
        d.field("flags", &self.flags());
        d.field("min_key_size", &self.min_key_size());
        d.field("max_key_size", &self.max_key_size());
        d.finish()
    }
}

/// A value that identifies a mechanism type.
///
/// Mechanism types are defined with the objects and mechanism descriptions that
/// use them.
///
/// Vendor defined values for this type may also be specified.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum MechanismType {
    Acti,
    ActiKeyGen,
    AesCbc,
    AesCbcEncryptData,
    AesCbcPad,
    AesCcm,
    AesCfb1,
    AesCfb8,
    AesCfb64,
    AesCfb128,
    AesCmac,
    AesCmacGeneral,
    AesCtr,
    AesCts,
    AesEcb,
    AesEcbEncryptData,
    AesGcm,
    AesGmac,
    AesKeyGen,
    AesKeyWrap,
    AesKeyWrapPad,
    AesMac,
    AesMacGeneral,
    AesOfb,
    AesXcbcMac,
    AesXcbcMac96,
    AriaCbc,
    AriaCbcEncryptData,
    AriaCbcPad,
    AriaEcb,
    AriaEcbEncryptData,
    AriaKeyGen,
    AriaMac,
    AriaMacGeneral,
    BatonCbc128,
    BatonCounter,
    BatonEcb96,
    BatonEcb128,
    BatonKeyGen,
    BatonShuffle,
    BatonWrap,
    BlowfishCbc,
    BlowfishCbcPad,
    BlowfishKeyGen,
    CamelliaCbc,
    CamelliaCbcEncryptData,
    CamelliaCbcPad,
    CamelliaCtr,
    CamelliaEcb,
    CamelliaEcbEncryptData,
    CamelliaKeyGen,
    CamelliaMac,
    CamelliaMacGeneral,
    Cast3KeyGen,
    Cast3Ecb,
    Cast3Cbc,
    Cast3Mac,
    Cast3MacGeneral,
    Cast3CbcPad,
    Cast5KeyGen,
    Cast5Ecb,
    Cast5Cbc,
    Cast5Mac,
    Cast5MacGeneral,
    Cast5CbcPad,
    Cast128KeyGen,
    Cast128Ecb,
    Cast128Cbc,
    Cast128Mac,
    Cast128MacGeneral,
    Cast128CbcPad,
    CastCbc,
    CastCbcPad,
    CastEcb,
    CastKeyGen,
    CastMac,
    CastMacGeneral,
    CdmfCbc,
    CdmfCbcPad,
    CdmfEcb,
    CdmfKeyGen,
    CdmfMac,
    CdmfMacGeneral,
    CmsSig,
    ConcatenateBaseAndData,
    ConcatenateBaseAndKey,
    ConcatenateDataAndBase,
    Des2KeyGen,
    Des3KeyGen,
    Des3Ecb,
    Des3Cbc,
    Des3Mac,
    Des3MacGeneral,
    Des3CbcPad,
    Des3CmacGeneral,
    Des3Cmac,
    Des3EcbEncryptData,
    Des3CbcEncryptData,
    DesCbc,
    DesCbcEncryptData,
    DesCbcPad,
    DesCfb8,
    DesCfb64,
    DesEcb,
    DesEcbEncryptData,
    DesKeyGen,
    DesMac,
    DesMacGeneral,
    DesOfb8,
    DesOfb64,
    DhPkcsDerive,
    DhPkcsKeyPairGen,
    DhPkcsParameterGen,
    Dsa,
    DsaKeyPairGen,
    DsaParameterGen,
    DsaProbablisticParameterGen,
    DsaSha1,
    DsaSha224,
    DsaSha256,
    DsaSha384,
    DsaSha512,
    DsaShaweTaylorParameterGen,
    Ecdh1Derive,
    Ecdh1CofactorDerive,
    EcdhAesKeyWrap,
    Ecdsa,
    EcdsaKeyPairGen,
    EcdsaSha1,
    EcdsaSha224,
    EcdsaSha256,
    EcdsaSha384,
    EcdsaSha512,
    EcmqvDerive,
    EcKeyPairGen,
    ExtractKeyFromKey,
    Fasthash,
    FortezzaTimestamp,
    GenericSecretKeyGen,
    Gost28147KeyGen,
    Gost28147Ecb,
    Gost28147,
    Gost28147Mac,
    Gost28147KeyWrap,
    Gostr3410KeyPairGen,
    Gostr3410,
    Gostr3410KeyWrap,
    Gostr3410Derive,
    Gostr3411,
    Gostr3411Hmac,
    Gostr3410WithGostr3411,
    Hotp,
    HotpKeyGen,
    IdeaCbc,
    IdeaCbcPad,
    IdeaEcb,
    IdeaKeyGen,
    IdeaMac,
    IdeaMacGeneral,
    JuniperCbc128,
    JuniperCounter,
    JuniperEcb128,
    JuniperKeyGen,
    JuniperShuffle,
    JuniperWrap,
    KeaDerive,
    KeaKeyDerive,
    KeaKeyPairGen,
    KeyWrapLynks,
    KeyWrapSetOaep,
    KipDerive,
    KipMac,
    KipWrap,
    Md2RsaPkcs,
    Md2,
    Md2Hmac,
    Md2HmacGeneral,
    Md2KeyDerivation,
    Md5RsaPkcs,
    Md5,
    Md5Hmac,
    Md5HmacGeneral,
    Md5KeyDerivation,
    PbaSha1WithSha1Hmac,
    PbeMd2DesCbc,
    PbeMd5DesCbc,
    PbeMd5CastCbc,
    PbeMd5Cast3Cbc,
    PbeMd5Cast5Cbc,
    PbeMd5Cast128Cbc,
    PbeSha1Cast5Cbc,
    PbeSha1Cast128Cbc,
    PbeSha1Des2EdeCbc,
    PbeSha1Des3EdeCbc,
    PbeSha1Rc2_40Cbc,
    PbeSha1Rc2_128Cbc,
    PbeSha1Rc4_40,
    PbeSha1Rc4_128,
    Pkcs5Pbkd2,
    Rc2KeyGen,
    Rc2Ecb,
    Rc2Cbc,
    Rc2Mac,
    Rc2MacGeneral,
    Rc2CbcPad,
    Rc4KeyGen,
    Rc4,
    Rc5KeyGen,
    Rc5Ecb,
    Rc5Cbc,
    Rc5Mac,
    Rc5MacGeneral,
    Rrc5CbcPad,
    Ripemd128RsaPkcs,
    Ripemd128,
    Ripemd128Hmac,
    Ripemd128HmacGeneral,
    Ripemd160RsaPkcs,
    Ripemd160,
    Ripemd160Hmac,
    Ripemd160HmacGeneral,
    Rsa9796,
    RsaAesKeyWrap,
    RsaPkcs,
    RsaPkcsKeyPairGen,
    RsaPkcsOaep,
    RsaPkcsOaepTpm11,
    RsaPkcsPss,
    RsaPkcsTpm11,
    RsaX9_31KeyPairGen,
    RsaX9_31,
    RsaX509,
    Securid,
    SecuridKeyGen,
    SeedCbc,
    SeedCbcEncryptData,
    SeedCbcPad,
    SeedEcb,
    SeedEcbEncryptData,
    SeedKeyGen,
    SeedMac,
    SeedMacGeneral,
    Sha1RsaPkcs,
    Sha1RsaPkcsPss,
    Sha1KeyDerivation,
    Sha224RsaPkcs,
    Sha224RsaPkcsPss,
    Sha224,
    Sha224Hmac,
    Sha224HmacGeneral,
    Sha224KeyDerivation,
    Sha256RsaPkcs,
    Sha256RsaPkcsPss,
    Sha256,
    Sha256Hmac,
    Sha256HmacGeneral,
    Sha256KeyDerivation,
    Sha384RsaPkcs,
    Sha384RsaPkcsPss,
    Sha384,
    Sha384Hmac,
    Sha384HmacGeneral,
    Sha384KeyDerivation,
    Sha512RsaPkcs,
    Sha512RsaPkcsPss,
    Sha512T,
    Sha512THmac,
    Sha512THmacGeneral,
    Sha512TKeyDerivation,
    Sha512,
    Sha512Hmac,
    Sha512HmacGeneral,
    Sha512KeyDerivation,
    Sha1RsaX9_31,
    Sha512_224,
    Sha512_224Hmac,
    Sha512_224HmacGeneral,
    Sha512_224KeyDerivation,
    Sha512_256,
    Sha512_256Hmac,
    Sha512_256HmacGeneral,
    Sha512_256KeyDerivation,
    Sha1,
    Sha1Hmac,
    Sha1HmacGeneral,
    SkipjackCbc64,
    SkipjackCfb8,
    SkipjackCfb16,
    SkipjackCfb32,
    SkipjackCfb64,
    SkipjackEcb64,
    SkipjackKeyGen,
    SkipjackOfb64,
    SkipjackPrivateWrap,
    SkipjackRelayx,
    SkipjackWrap,
    Ssl3PreMasterKeyGen,
    Ssl3MasterKeyDerive,
    Ssl3KeyAndMacDerive,
    Ssl3MasterKeyDeriveDh,
    Ssl3Md5Mac,
    Ssl3Sha1Mac,
    Tls10MacServer,
    Tls10MacClient,
    Tls12Mac,
    Tls12Kdf,
    Tls12MasterKeyDerive,
    Tls12KeyAndMacDerive,
    Tls12MasterKeyDeriveDh,
    Tls12KeySafeDerive,
    TlsKdf,
    TlsKeyAndMacDerive,
    TlsMac,
    TlsMasterKeyDerive,
    TlsMasterKeyDeriveDh,
    TlsPreMasterKeyGen,
    TlsPrf,
    TwofishCbc,
    TwofishCbcPad,
    TwofishKeyGen,
    VendorDefined,
    WtlsClientKeyAndMacDerive,
    WtlsMasterKeyDerive,
    WtlsMasterKeyDeriveDhEcc,
    WtlsPreMasterKeyGen,
    WtlsPrf,
    WtlsServerKeyAndMacDerive,
    X9_42DhKeyPairGen,
    X9_42DhDerive,
    X9_42DhHybridDerive,
    X9_42MqvDerive,
    X9_42DhParameterGen,
    XorBaseAndData,
}

impl Mechanism for MechanismType {
    fn r#type(&self) -> MechanismType {
        *self
    }

    fn as_ptr(&self) -> *const c_void {
        std::ptr::null()
    }

    fn len(&self) -> CK_ULONG {
        0
    }
}

impl From<MechanismType> for CK_MECHANISM_TYPE {
    fn from(mechanism_type: MechanismType) -> CK_MECHANISM_TYPE {
        match mechanism_type {
            MechanismType::Acti => CKM_ACTI as CK_MECHANISM_TYPE,
            MechanismType::ActiKeyGen => CKM_ACTI_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::AesCbc => CKM_AES_CBC as CK_MECHANISM_TYPE,
            MechanismType::AesCbcEncryptData => CKM_AES_CBC_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::AesCbcPad => CKM_AES_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::AesCcm => CKM_AES_CCM as CK_MECHANISM_TYPE,
            MechanismType::AesCfb1 => CKM_AES_CFB1 as CK_MECHANISM_TYPE,
            MechanismType::AesCfb8 => CKM_AES_CFB8 as CK_MECHANISM_TYPE,
            MechanismType::AesCfb64 => CKM_AES_CFB64 as CK_MECHANISM_TYPE,
            MechanismType::AesCfb128 => CKM_AES_CFB128 as CK_MECHANISM_TYPE,
            MechanismType::AesCmac => CKM_AES_CMAC as CK_MECHANISM_TYPE,
            MechanismType::AesCmacGeneral => CKM_AES_CMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::AesCtr => CKM_AES_CTR as CK_MECHANISM_TYPE,
            MechanismType::AesCts => CKM_AES_CTS as CK_MECHANISM_TYPE,
            MechanismType::AesEcb => CKM_AES_ECB as CK_MECHANISM_TYPE,
            MechanismType::AesEcbEncryptData => CKM_AES_ECB_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::AesGcm => CKM_AES_GCM as CK_MECHANISM_TYPE,
            MechanismType::AesGmac => CKM_AES_GMAC as CK_MECHANISM_TYPE,
            MechanismType::AesKeyGen => CKM_AES_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::AesKeyWrap => CKM_AES_KEY_WRAP as CK_MECHANISM_TYPE,
            MechanismType::AesKeyWrapPad => CKM_AES_KEY_WRAP_PAD as CK_MECHANISM_TYPE,
            MechanismType::AesMac => CKM_AES_MAC as CK_MECHANISM_TYPE,
            MechanismType::AesMacGeneral => CKM_AES_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::AesOfb => CKM_AES_OFB as CK_MECHANISM_TYPE,
            MechanismType::AesXcbcMac => CKM_AES_XCBC_MAC as CK_MECHANISM_TYPE,
            MechanismType::AesXcbcMac96 => CKM_AES_XCBC_MAC_96 as CK_MECHANISM_TYPE,
            MechanismType::AriaCbc => CKM_ARIA_CBC as CK_MECHANISM_TYPE,
            MechanismType::AriaCbcEncryptData => CKM_ARIA_CBC_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::AriaCbcPad => CKM_ARIA_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::AriaEcb => CKM_ARIA_ECB as CK_MECHANISM_TYPE,
            MechanismType::AriaEcbEncryptData => CKM_ARIA_ECB_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::AriaKeyGen => CKM_ARIA_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::AriaMac => CKM_ARIA_MAC as CK_MECHANISM_TYPE,
            MechanismType::AriaMacGeneral => CKM_ARIA_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::BatonCbc128 => CKM_BATON_CBC128 as CK_MECHANISM_TYPE,
            MechanismType::BatonCounter => CKM_BATON_COUNTER as CK_MECHANISM_TYPE,
            MechanismType::BatonEcb96 => CKM_BATON_ECB96 as CK_MECHANISM_TYPE,
            MechanismType::BatonEcb128 => CKM_BATON_ECB128 as CK_MECHANISM_TYPE,
            MechanismType::BatonKeyGen => CKM_BATON_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::BatonShuffle => CKM_BATON_SHUFFLE as CK_MECHANISM_TYPE,
            MechanismType::BatonWrap => CKM_BATON_WRAP as CK_MECHANISM_TYPE,
            MechanismType::BlowfishCbc => CKM_BLOWFISH_CBC as CK_MECHANISM_TYPE,
            MechanismType::BlowfishCbcPad => CKM_BLOWFISH_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::BlowfishKeyGen => CKM_BLOWFISH_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::CamelliaCbc => CKM_CAMELLIA_CBC as CK_MECHANISM_TYPE,
            MechanismType::CamelliaCbcEncryptData => {
                CKM_CAMELLIA_CBC_ENCRYPT_DATA as CK_MECHANISM_TYPE
            }
            MechanismType::CamelliaCbcPad => CKM_CAMELLIA_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::CamelliaCtr => CKM_CAMELLIA_CTR as CK_MECHANISM_TYPE,
            MechanismType::CamelliaEcb => CKM_CAMELLIA_ECB as CK_MECHANISM_TYPE,
            MechanismType::CamelliaEcbEncryptData => {
                CKM_CAMELLIA_ECB_ENCRYPT_DATA as CK_MECHANISM_TYPE
            }
            MechanismType::CamelliaKeyGen => CKM_CAMELLIA_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::CamelliaMac => CKM_CAMELLIA_MAC as CK_MECHANISM_TYPE,
            MechanismType::CamelliaMacGeneral => CKM_CAMELLIA_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Cast3KeyGen => CKM_CAST3_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Cast3Ecb => CKM_CAST3_ECB as CK_MECHANISM_TYPE,
            MechanismType::Cast3Cbc => CKM_CAST3_CBC as CK_MECHANISM_TYPE,
            MechanismType::Cast3Mac => CKM_CAST3_MAC as CK_MECHANISM_TYPE,
            MechanismType::Cast3MacGeneral => CKM_CAST3_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Cast3CbcPad => CKM_CAST3_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::Cast5KeyGen => CKM_CAST5_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Cast5Ecb => CKM_CAST5_ECB as CK_MECHANISM_TYPE,
            MechanismType::Cast5Cbc => CKM_CAST5_CBC as CK_MECHANISM_TYPE,
            MechanismType::Cast5Mac => CKM_CAST5_MAC as CK_MECHANISM_TYPE,
            MechanismType::Cast5MacGeneral => CKM_CAST5_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Cast5CbcPad => CKM_CAST5_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::Cast128KeyGen => CKM_CAST128_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Cast128Ecb => CKM_CAST128_ECB as CK_MECHANISM_TYPE,
            MechanismType::Cast128Cbc => CKM_CAST128_CBC as CK_MECHANISM_TYPE,
            MechanismType::Cast128Mac => CKM_CAST128_MAC as CK_MECHANISM_TYPE,
            MechanismType::Cast128MacGeneral => CKM_CAST128_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Cast128CbcPad => CKM_CAST128_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::CastCbc => CKM_CAST_CBC as CK_MECHANISM_TYPE,
            MechanismType::CastCbcPad => CKM_CAST_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::CastEcb => CKM_CAST_ECB as CK_MECHANISM_TYPE,
            MechanismType::CastKeyGen => CKM_CAST_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::CastMac => CKM_CAST_MAC as CK_MECHANISM_TYPE,
            MechanismType::CastMacGeneral => CKM_CAST_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::CdmfCbc => CKM_CDMF_CBC as CK_MECHANISM_TYPE,
            MechanismType::CdmfCbcPad => CKM_CDMF_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::CdmfEcb => CKM_CDMF_ECB as CK_MECHANISM_TYPE,
            MechanismType::CdmfKeyGen => CKM_CDMF_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::CdmfMac => CKM_CDMF_MAC as CK_MECHANISM_TYPE,
            MechanismType::CdmfMacGeneral => CKM_CDMF_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::CmsSig => CKM_CMS_SIG as CK_MECHANISM_TYPE,
            MechanismType::ConcatenateBaseAndData => {
                CKM_CONCATENATE_BASE_AND_DATA as CK_MECHANISM_TYPE
            }
            MechanismType::ConcatenateBaseAndKey => {
                CKM_CONCATENATE_BASE_AND_KEY as CK_MECHANISM_TYPE
            }
            MechanismType::ConcatenateDataAndBase => {
                CKM_CONCATENATE_DATA_AND_BASE as CK_MECHANISM_TYPE
            }
            MechanismType::Des2KeyGen => CKM_DES2_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Des3KeyGen => CKM_DES3_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Des3Ecb => CKM_DES3_ECB as CK_MECHANISM_TYPE,
            MechanismType::Des3Cbc => CKM_DES3_CBC as CK_MECHANISM_TYPE,
            MechanismType::Des3Mac => CKM_DES3_MAC as CK_MECHANISM_TYPE,
            MechanismType::Des3MacGeneral => CKM_DES3_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Des3CbcPad => CKM_DES3_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::Des3CmacGeneral => CKM_DES3_CMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Des3Cmac => CKM_DES3_CMAC as CK_MECHANISM_TYPE,
            MechanismType::Des3EcbEncryptData => CKM_DES3_ECB_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::Des3CbcEncryptData => CKM_DES3_CBC_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::DesCbc => CKM_DES_CBC as CK_MECHANISM_TYPE,
            MechanismType::DesCbcEncryptData => CKM_DES_CBC_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::DesCbcPad => CKM_DES_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::DesCfb8 => CKM_DES_CFB8 as CK_MECHANISM_TYPE,
            MechanismType::DesCfb64 => CKM_DES_CFB64 as CK_MECHANISM_TYPE,
            MechanismType::DesEcb => CKM_DES_ECB as CK_MECHANISM_TYPE,
            MechanismType::DesEcbEncryptData => CKM_DES_ECB_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::DesKeyGen => CKM_DES_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::DesMac => CKM_DES_MAC as CK_MECHANISM_TYPE,
            MechanismType::DesMacGeneral => CKM_DES_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::DesOfb8 => CKM_DES_OFB8 as CK_MECHANISM_TYPE,
            MechanismType::DesOfb64 => CKM_DES_OFB64 as CK_MECHANISM_TYPE,
            MechanismType::DhPkcsDerive => CKM_DH_PKCS_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::DhPkcsKeyPairGen => CKM_DH_PKCS_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::DhPkcsParameterGen => CKM_DH_PKCS_PARAMETER_GEN as CK_MECHANISM_TYPE,
            MechanismType::Dsa => CKM_DSA as CK_MECHANISM_TYPE,
            MechanismType::DsaKeyPairGen => CKM_DSA_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::DsaParameterGen => CKM_DSA_PARAMETER_GEN as CK_MECHANISM_TYPE,
            MechanismType::DsaProbablisticParameterGen => {
                CKM_DSA_PROBABLISTIC_PARAMETER_GEN as CK_MECHANISM_TYPE
            }
            MechanismType::DsaSha1 => CKM_DSA_SHA1 as CK_MECHANISM_TYPE,
            MechanismType::DsaSha224 => CKM_DSA_SHA224 as CK_MECHANISM_TYPE,
            MechanismType::DsaSha256 => CKM_DSA_SHA256 as CK_MECHANISM_TYPE,
            MechanismType::DsaSha384 => CKM_DSA_SHA384 as CK_MECHANISM_TYPE,
            MechanismType::DsaSha512 => CKM_DSA_SHA512 as CK_MECHANISM_TYPE,
            MechanismType::DsaShaweTaylorParameterGen => {
                CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN as CK_MECHANISM_TYPE
            }
            MechanismType::Ecdh1Derive => CKM_ECDH1_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::Ecdh1CofactorDerive => CKM_ECDH1_COFACTOR_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::EcdhAesKeyWrap => CKM_ECDH_AES_KEY_WRAP as CK_MECHANISM_TYPE,
            MechanismType::Ecdsa => CKM_ECDSA as CK_MECHANISM_TYPE,
            MechanismType::EcdsaKeyPairGen => CKM_ECDSA_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::EcdsaSha1 => CKM_ECDSA_SHA1 as CK_MECHANISM_TYPE,
            MechanismType::EcdsaSha224 => CKM_ECDSA_SHA224 as CK_MECHANISM_TYPE,
            MechanismType::EcdsaSha256 => CKM_ECDSA_SHA256 as CK_MECHANISM_TYPE,
            MechanismType::EcdsaSha384 => CKM_ECDSA_SHA384 as CK_MECHANISM_TYPE,
            MechanismType::EcdsaSha512 => CKM_ECDSA_SHA512 as CK_MECHANISM_TYPE,
            MechanismType::EcmqvDerive => CKM_ECMQV_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::EcKeyPairGen => CKM_EC_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::ExtractKeyFromKey => CKM_EXTRACT_KEY_FROM_KEY as CK_MECHANISM_TYPE,
            MechanismType::Fasthash => CKM_FASTHASH as CK_MECHANISM_TYPE,
            MechanismType::FortezzaTimestamp => CKM_FORTEZZA_TIMESTAMP as CK_MECHANISM_TYPE,
            MechanismType::GenericSecretKeyGen => CKM_GENERIC_SECRET_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Gost28147KeyGen => CKM_GOST28147_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Gost28147Ecb => CKM_GOST28147_ECB as CK_MECHANISM_TYPE,
            MechanismType::Gost28147 => CKM_GOST28147 as CK_MECHANISM_TYPE,
            MechanismType::Gost28147Mac => CKM_GOST28147_MAC as CK_MECHANISM_TYPE,
            MechanismType::Gost28147KeyWrap => CKM_GOST28147_KEY_WRAP as CK_MECHANISM_TYPE,
            MechanismType::Gostr3410KeyPairGen => CKM_GOSTR3410_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::Gostr3410 => CKM_GOSTR3410 as CK_MECHANISM_TYPE,
            MechanismType::Gostr3410KeyWrap => CKM_GOSTR3410_KEY_WRAP as CK_MECHANISM_TYPE,
            MechanismType::Gostr3410Derive => CKM_GOSTR3410_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::Gostr3411 => CKM_GOSTR3411 as CK_MECHANISM_TYPE,
            MechanismType::Gostr3411Hmac => CKM_GOSTR3411_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Gostr3410WithGostr3411 => {
                CKM_GOSTR3410_WITH_GOSTR3411 as CK_MECHANISM_TYPE
            }
            MechanismType::Hotp => CKM_HOTP as CK_MECHANISM_TYPE,
            MechanismType::HotpKeyGen => CKM_HOTP_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::IdeaCbc => CKM_IDEA_CBC as CK_MECHANISM_TYPE,
            MechanismType::IdeaCbcPad => CKM_IDEA_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::IdeaEcb => CKM_IDEA_ECB as CK_MECHANISM_TYPE,
            MechanismType::IdeaKeyGen => CKM_IDEA_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::IdeaMac => CKM_IDEA_MAC as CK_MECHANISM_TYPE,
            MechanismType::IdeaMacGeneral => CKM_IDEA_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::JuniperCbc128 => CKM_JUNIPER_CBC128 as CK_MECHANISM_TYPE,
            MechanismType::JuniperCounter => CKM_JUNIPER_COUNTER as CK_MECHANISM_TYPE,
            MechanismType::JuniperEcb128 => CKM_JUNIPER_ECB128 as CK_MECHANISM_TYPE,
            MechanismType::JuniperKeyGen => CKM_JUNIPER_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::JuniperShuffle => CKM_JUNIPER_SHUFFLE as CK_MECHANISM_TYPE,
            MechanismType::JuniperWrap => CKM_JUNIPER_WRAP as CK_MECHANISM_TYPE,
            MechanismType::KeaDerive => CKM_KEA_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::KeaKeyDerive => CKM_KEA_KEY_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::KeaKeyPairGen => CKM_KEA_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::KeyWrapLynks => CKM_KEY_WRAP_LYNKS as CK_MECHANISM_TYPE,
            MechanismType::KeyWrapSetOaep => CKM_KEY_WRAP_SET_OAEP as CK_MECHANISM_TYPE,
            MechanismType::KipDerive => CKM_KIP_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::KipMac => CKM_KIP_MAC as CK_MECHANISM_TYPE,
            MechanismType::KipWrap => CKM_KIP_WRAP as CK_MECHANISM_TYPE,
            MechanismType::Md2RsaPkcs => CKM_MD2_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Md2 => CKM_MD2 as CK_MECHANISM_TYPE,
            MechanismType::Md2Hmac => CKM_MD2_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Md2HmacGeneral => CKM_MD2_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Md2KeyDerivation => CKM_MD2_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Md5RsaPkcs => CKM_MD5_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Md5 => CKM_MD5 as CK_MECHANISM_TYPE,
            MechanismType::Md5Hmac => CKM_MD5_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Md5HmacGeneral => CKM_MD5_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Md5KeyDerivation => CKM_MD5_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::PbaSha1WithSha1Hmac => CKM_PBA_SHA1_WITH_SHA1_HMAC as CK_MECHANISM_TYPE,
            MechanismType::PbeMd2DesCbc => CKM_PBE_MD2_DES_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeMd5DesCbc => CKM_PBE_MD5_DES_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeMd5CastCbc => CKM_PBE_MD5_CAST_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeMd5Cast3Cbc => CKM_PBE_MD5_CAST3_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeMd5Cast5Cbc => CKM_PBE_MD5_CAST5_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeMd5Cast128Cbc => CKM_PBE_MD5_CAST128_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Cast5Cbc => CKM_PBE_SHA1_CAST5_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Cast128Cbc => CKM_PBE_SHA1_CAST128_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Des2EdeCbc => CKM_PBE_SHA1_DES2_EDE_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Des3EdeCbc => CKM_PBE_SHA1_DES3_EDE_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Rc2_40Cbc => CKM_PBE_SHA1_RC2_40_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Rc2_128Cbc => CKM_PBE_SHA1_RC2_128_CBC as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Rc4_40 => CKM_PBE_SHA1_RC4_40 as CK_MECHANISM_TYPE,
            MechanismType::PbeSha1Rc4_128 => CKM_PBE_SHA1_RC4_128 as CK_MECHANISM_TYPE,
            MechanismType::Pkcs5Pbkd2 => CKM_PKCS5_PBKD2 as CK_MECHANISM_TYPE,
            MechanismType::Rc2KeyGen => CKM_RC2_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Rc2Ecb => CKM_RC2_ECB as CK_MECHANISM_TYPE,
            MechanismType::Rc2Cbc => CKM_RC2_CBC as CK_MECHANISM_TYPE,
            MechanismType::Rc2Mac => CKM_RC2_MAC as CK_MECHANISM_TYPE,
            MechanismType::Rc2MacGeneral => CKM_RC2_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Rc2CbcPad => CKM_RC2_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::Rc4KeyGen => CKM_RC4_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Rc4 => CKM_RC4 as CK_MECHANISM_TYPE,
            MechanismType::Rc5KeyGen => CKM_RC5_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Rc5Ecb => CKM_RC5_ECB as CK_MECHANISM_TYPE,
            MechanismType::Rc5Cbc => CKM_RC5_CBC as CK_MECHANISM_TYPE,
            MechanismType::Rc5Mac => CKM_RC5_MAC as CK_MECHANISM_TYPE,
            MechanismType::Rc5MacGeneral => CKM_RC5_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Rrc5CbcPad => CKM_RC5_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::Ripemd128RsaPkcs => CKM_RIPEMD128_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Ripemd128 => CKM_RIPEMD128 as CK_MECHANISM_TYPE,
            MechanismType::Ripemd128Hmac => CKM_RIPEMD128_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Ripemd128HmacGeneral => CKM_RIPEMD128_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Ripemd160RsaPkcs => CKM_RIPEMD160_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Ripemd160 => CKM_RIPEMD160 as CK_MECHANISM_TYPE,
            MechanismType::Ripemd160Hmac => CKM_RIPEMD160_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Ripemd160HmacGeneral => CKM_RIPEMD160_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Rsa9796 => CKM_RSA_9796 as CK_MECHANISM_TYPE,
            MechanismType::RsaAesKeyWrap => CKM_RSA_AES_KEY_WRAP as CK_MECHANISM_TYPE,
            MechanismType::RsaPkcs => CKM_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::RsaPkcsKeyPairGen => CKM_RSA_PKCS_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::RsaPkcsOaep => CKM_RSA_PKCS_OAEP as CK_MECHANISM_TYPE,
            MechanismType::RsaPkcsOaepTpm11 => CKM_RSA_PKCS_OAEP_TPM_1_1 as CK_MECHANISM_TYPE,
            MechanismType::RsaPkcsPss => CKM_RSA_PKCS_PSS as CK_MECHANISM_TYPE,
            MechanismType::RsaPkcsTpm11 => CKM_RSA_PKCS_TPM_1_1 as CK_MECHANISM_TYPE,
            MechanismType::RsaX9_31KeyPairGen => CKM_RSA_X9_31_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::RsaX9_31 => CKM_RSA_X9_31 as CK_MECHANISM_TYPE,
            MechanismType::RsaX509 => CKM_RSA_X_509 as CK_MECHANISM_TYPE,
            MechanismType::Securid => CKM_SECURID as CK_MECHANISM_TYPE,
            MechanismType::SecuridKeyGen => CKM_SECURID_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::SeedCbc => CKM_SEED_CBC as CK_MECHANISM_TYPE,
            MechanismType::SeedCbcEncryptData => CKM_SEED_CBC_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::SeedCbcPad => CKM_SEED_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::SeedEcb => CKM_SEED_ECB as CK_MECHANISM_TYPE,
            MechanismType::SeedEcbEncryptData => CKM_SEED_ECB_ENCRYPT_DATA as CK_MECHANISM_TYPE,
            MechanismType::SeedKeyGen => CKM_SEED_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::SeedMac => CKM_SEED_MAC as CK_MECHANISM_TYPE,
            MechanismType::SeedMacGeneral => CKM_SEED_MAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Sha1RsaPkcs => CKM_SHA1_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Sha1RsaPkcsPss => CKM_SHA1_RSA_PKCS_PSS as CK_MECHANISM_TYPE,
            MechanismType::Sha1KeyDerivation => CKM_SHA1_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Sha224RsaPkcs => CKM_SHA224_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Sha224RsaPkcsPss => CKM_SHA224_RSA_PKCS_PSS as CK_MECHANISM_TYPE,
            MechanismType::Sha224 => CKM_SHA224 as CK_MECHANISM_TYPE,
            MechanismType::Sha224Hmac => CKM_SHA224_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha224HmacGeneral => CKM_SHA224_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Sha224KeyDerivation => CKM_SHA224_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Sha256RsaPkcs => CKM_SHA256_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Sha256RsaPkcsPss => CKM_SHA256_RSA_PKCS_PSS as CK_MECHANISM_TYPE,
            MechanismType::Sha256 => CKM_SHA256 as CK_MECHANISM_TYPE,
            MechanismType::Sha256Hmac => CKM_SHA256_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha256HmacGeneral => CKM_SHA256_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Sha256KeyDerivation => CKM_SHA256_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Sha384RsaPkcs => CKM_SHA384_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Sha384RsaPkcsPss => CKM_SHA384_RSA_PKCS_PSS as CK_MECHANISM_TYPE,
            MechanismType::Sha384 => CKM_SHA384 as CK_MECHANISM_TYPE,
            MechanismType::Sha384Hmac => CKM_SHA384_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha384HmacGeneral => CKM_SHA384_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Sha384KeyDerivation => CKM_SHA384_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Sha512RsaPkcs => CKM_SHA512_RSA_PKCS as CK_MECHANISM_TYPE,
            MechanismType::Sha512RsaPkcsPss => CKM_SHA512_RSA_PKCS_PSS as CK_MECHANISM_TYPE,
            MechanismType::Sha512T => CKM_SHA512_T as CK_MECHANISM_TYPE,
            MechanismType::Sha512THmac => CKM_SHA512_T_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha512THmacGeneral => CKM_SHA512_T_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Sha512TKeyDerivation => CKM_SHA512_T_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Sha512 => CKM_SHA512 as CK_MECHANISM_TYPE,
            MechanismType::Sha512Hmac => CKM_SHA512_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha512HmacGeneral => CKM_SHA512_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::Sha512KeyDerivation => CKM_SHA512_KEY_DERIVATION as CK_MECHANISM_TYPE,
            MechanismType::Sha1RsaX9_31 => CKM_SHA1_RSA_X9_31 as CK_MECHANISM_TYPE,
            MechanismType::Sha512_224 => CKM_SHA512_224 as CK_MECHANISM_TYPE,
            MechanismType::Sha512_224Hmac => CKM_SHA512_224_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha512_224HmacGeneral => {
                CKM_SHA512_224_HMAC_GENERAL as CK_MECHANISM_TYPE
            }
            MechanismType::Sha512_224KeyDerivation => {
                CKM_SHA512_224_KEY_DERIVATION as CK_MECHANISM_TYPE
            }
            MechanismType::Sha512_256 => CKM_SHA512_256 as CK_MECHANISM_TYPE,
            MechanismType::Sha512_256Hmac => CKM_SHA512_256_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha512_256HmacGeneral => {
                CKM_SHA512_256_HMAC_GENERAL as CK_MECHANISM_TYPE
            }
            MechanismType::Sha512_256KeyDerivation => {
                CKM_SHA512_256_KEY_DERIVATION as CK_MECHANISM_TYPE
            }
            MechanismType::Sha1 => CKM_SHA_1 as CK_MECHANISM_TYPE,
            MechanismType::Sha1Hmac => CKM_SHA_1_HMAC as CK_MECHANISM_TYPE,
            MechanismType::Sha1HmacGeneral => CKM_SHA_1_HMAC_GENERAL as CK_MECHANISM_TYPE,
            MechanismType::SkipjackCbc64 => CKM_SKIPJACK_CBC64 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackCfb8 => CKM_SKIPJACK_CFB8 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackCfb16 => CKM_SKIPJACK_CFB16 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackCfb32 => CKM_SKIPJACK_CFB32 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackCfb64 => CKM_SKIPJACK_CFB64 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackEcb64 => CKM_SKIPJACK_ECB64 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackKeyGen => CKM_SKIPJACK_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::SkipjackOfb64 => CKM_SKIPJACK_OFB64 as CK_MECHANISM_TYPE,
            MechanismType::SkipjackPrivateWrap => CKM_SKIPJACK_PRIVATE_WRAP as CK_MECHANISM_TYPE,
            MechanismType::SkipjackRelayx => CKM_SKIPJACK_RELAYX as CK_MECHANISM_TYPE,
            MechanismType::SkipjackWrap => CKM_SKIPJACK_WRAP as CK_MECHANISM_TYPE,
            MechanismType::Ssl3PreMasterKeyGen => CKM_SSL3_PRE_MASTER_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::Ssl3MasterKeyDerive => CKM_SSL3_MASTER_KEY_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::Ssl3KeyAndMacDerive => CKM_SSL3_KEY_AND_MAC_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::Ssl3MasterKeyDeriveDh => {
                CKM_SSL3_MASTER_KEY_DERIVE_DH as CK_MECHANISM_TYPE
            }
            MechanismType::Ssl3Md5Mac => CKM_SSL3_MD5_MAC as CK_MECHANISM_TYPE,
            MechanismType::Ssl3Sha1Mac => CKM_SSL3_SHA1_MAC as CK_MECHANISM_TYPE,
            MechanismType::Tls10MacServer => CKM_TLS10_MAC_SERVER as CK_MECHANISM_TYPE,
            MechanismType::Tls10MacClient => CKM_TLS10_MAC_CLIENT as CK_MECHANISM_TYPE,
            MechanismType::Tls12Mac => CKM_TLS12_MAC as CK_MECHANISM_TYPE,
            MechanismType::Tls12Kdf => CKM_TLS12_KDF as CK_MECHANISM_TYPE,
            MechanismType::Tls12MasterKeyDerive => CKM_TLS12_MASTER_KEY_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::Tls12KeyAndMacDerive => {
                CKM_TLS12_KEY_AND_MAC_DERIVE as CK_MECHANISM_TYPE
            }
            MechanismType::Tls12MasterKeyDeriveDh => {
                CKM_TLS12_MASTER_KEY_DERIVE_DH as CK_MECHANISM_TYPE
            }
            MechanismType::Tls12KeySafeDerive => CKM_TLS12_KEY_SAFE_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::TlsKdf => CKM_TLS_KDF as CK_MECHANISM_TYPE,
            MechanismType::TlsKeyAndMacDerive => CKM_TLS_KEY_AND_MAC_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::TlsMac => CKM_TLS_MAC as CK_MECHANISM_TYPE,
            MechanismType::TlsMasterKeyDerive => CKM_TLS_MASTER_KEY_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::TlsMasterKeyDeriveDh => {
                CKM_TLS_MASTER_KEY_DERIVE_DH as CK_MECHANISM_TYPE
            }
            MechanismType::TlsPreMasterKeyGen => CKM_TLS_PRE_MASTER_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::TlsPrf => CKM_TLS_PRF as CK_MECHANISM_TYPE,
            MechanismType::TwofishCbc => CKM_TWOFISH_CBC as CK_MECHANISM_TYPE,
            MechanismType::TwofishCbcPad => CKM_TWOFISH_CBC_PAD as CK_MECHANISM_TYPE,
            MechanismType::TwofishKeyGen => CKM_TWOFISH_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::VendorDefined => CKM_VENDOR_DEFINED as CK_MECHANISM_TYPE,
            MechanismType::WtlsClientKeyAndMacDerive => {
                CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE as CK_MECHANISM_TYPE
            }
            MechanismType::WtlsMasterKeyDerive => CKM_WTLS_MASTER_KEY_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::WtlsMasterKeyDeriveDhEcc => {
                CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC as CK_MECHANISM_TYPE
            }
            MechanismType::WtlsPreMasterKeyGen => CKM_WTLS_PRE_MASTER_KEY_GEN as CK_MECHANISM_TYPE,
            MechanismType::WtlsPrf => CKM_WTLS_PRF as CK_MECHANISM_TYPE,
            MechanismType::WtlsServerKeyAndMacDerive => {
                CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE as CK_MECHANISM_TYPE
            }
            MechanismType::X9_42DhKeyPairGen => CKM_X9_42_DH_KEY_PAIR_GEN as CK_MECHANISM_TYPE,
            MechanismType::X9_42DhDerive => CKM_X9_42_DH_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::X9_42DhHybridDerive => CKM_X9_42_DH_HYBRID_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::X9_42MqvDerive => CKM_X9_42_MQV_DERIVE as CK_MECHANISM_TYPE,
            MechanismType::X9_42DhParameterGen => CKM_X9_42_DH_PARAMETER_GEN as CK_MECHANISM_TYPE,
            MechanismType::XorBaseAndData => CKM_XOR_BASE_AND_DATA as CK_MECHANISM_TYPE,
        }
    }
}

impl From<CK_MECHANISM_TYPE> for MechanismType {
    fn from(mechanism_type: CK_MECHANISM_TYPE) -> MechanismType {
        match mechanism_type as u32 {
            CKM_ACTI => MechanismType::Acti,
            CKM_ACTI_KEY_GEN => MechanismType::ActiKeyGen,
            CKM_AES_CBC => MechanismType::AesCbc,
            CKM_AES_CBC_ENCRYPT_DATA => MechanismType::AesCbcEncryptData,
            CKM_AES_CBC_PAD => MechanismType::AesCbcPad,
            CKM_AES_CCM => MechanismType::AesCcm,
            CKM_AES_CFB1 => MechanismType::AesCfb1,
            CKM_AES_CFB8 => MechanismType::AesCfb8,
            CKM_AES_CFB64 => MechanismType::AesCfb64,
            CKM_AES_CFB128 => MechanismType::AesCfb128,
            CKM_AES_CMAC => MechanismType::AesCmac,
            CKM_AES_CMAC_GENERAL => MechanismType::AesCmacGeneral,
            CKM_AES_CTR => MechanismType::AesCtr,
            CKM_AES_CTS => MechanismType::AesCts,
            CKM_AES_ECB => MechanismType::AesEcb,
            CKM_AES_ECB_ENCRYPT_DATA => MechanismType::AesEcbEncryptData,
            CKM_AES_GCM => MechanismType::AesGcm,
            CKM_AES_GMAC => MechanismType::AesGmac,
            CKM_AES_KEY_GEN => MechanismType::AesKeyGen,
            CKM_AES_KEY_WRAP => MechanismType::AesKeyWrap,
            CKM_AES_KEY_WRAP_PAD => MechanismType::AesKeyWrapPad,
            CKM_AES_MAC => MechanismType::AesMac,
            CKM_AES_MAC_GENERAL => MechanismType::AesMacGeneral,
            CKM_AES_OFB => MechanismType::AesOfb,
            CKM_AES_XCBC_MAC => MechanismType::AesXcbcMac,
            CKM_AES_XCBC_MAC_96 => MechanismType::AesXcbcMac96,
            CKM_ARIA_CBC => MechanismType::AriaCbc,
            CKM_ARIA_CBC_ENCRYPT_DATA => MechanismType::AriaCbcEncryptData,
            CKM_ARIA_CBC_PAD => MechanismType::AriaCbcPad,
            CKM_ARIA_ECB => MechanismType::AriaEcb,
            CKM_ARIA_ECB_ENCRYPT_DATA => MechanismType::AriaEcbEncryptData,
            CKM_ARIA_KEY_GEN => MechanismType::AriaKeyGen,
            CKM_ARIA_MAC => MechanismType::AriaMac,
            CKM_ARIA_MAC_GENERAL => MechanismType::AriaMacGeneral,
            CKM_BATON_CBC128 => MechanismType::BatonCbc128,
            CKM_BATON_COUNTER => MechanismType::BatonCounter,
            CKM_BATON_ECB96 => MechanismType::BatonEcb96,
            CKM_BATON_ECB128 => MechanismType::BatonEcb128,
            CKM_BATON_KEY_GEN => MechanismType::BatonKeyGen,
            CKM_BATON_SHUFFLE => MechanismType::BatonShuffle,
            CKM_BATON_WRAP => MechanismType::BatonWrap,
            CKM_BLOWFISH_CBC => MechanismType::BlowfishCbc,
            CKM_BLOWFISH_CBC_PAD => MechanismType::BlowfishCbcPad,
            CKM_BLOWFISH_KEY_GEN => MechanismType::BlowfishKeyGen,
            CKM_CAMELLIA_CBC => MechanismType::CamelliaCbc,
            CKM_CAMELLIA_CBC_ENCRYPT_DATA => MechanismType::CamelliaCbcEncryptData,
            CKM_CAMELLIA_CBC_PAD => MechanismType::CamelliaCbcPad,
            CKM_CAMELLIA_CTR => MechanismType::CamelliaCtr,
            CKM_CAMELLIA_ECB => MechanismType::CamelliaEcb,
            CKM_CAMELLIA_ECB_ENCRYPT_DATA => MechanismType::CamelliaEcbEncryptData,
            CKM_CAMELLIA_KEY_GEN => MechanismType::CamelliaKeyGen,
            CKM_CAMELLIA_MAC => MechanismType::CamelliaMac,
            CKM_CAMELLIA_MAC_GENERAL => MechanismType::CamelliaMacGeneral,
            CKM_CAST3_KEY_GEN => MechanismType::Cast3KeyGen,
            CKM_CAST3_ECB => MechanismType::Cast3Ecb,
            CKM_CAST3_CBC => MechanismType::Cast3Cbc,
            CKM_CAST3_MAC => MechanismType::Cast3Mac,
            CKM_CAST3_MAC_GENERAL => MechanismType::Cast3MacGeneral,
            CKM_CAST3_CBC_PAD => MechanismType::Cast3CbcPad,
            CKM_CAST5_KEY_GEN => MechanismType::Cast5KeyGen,
            CKM_CAST5_ECB => MechanismType::Cast5Ecb,
            CKM_CAST5_CBC => MechanismType::Cast5Cbc,
            CKM_CAST5_MAC => MechanismType::Cast5Mac,
            CKM_CAST5_MAC_GENERAL => MechanismType::Cast5MacGeneral,
            CKM_CAST5_CBC_PAD => MechanismType::Cast5CbcPad,
            CKM_CAST_CBC => MechanismType::CastCbc,
            CKM_CAST_CBC_PAD => MechanismType::CastCbcPad,
            CKM_CAST_ECB => MechanismType::CastEcb,
            CKM_CAST_KEY_GEN => MechanismType::CastKeyGen,
            CKM_CAST_MAC => MechanismType::CastMac,
            CKM_CAST_MAC_GENERAL => MechanismType::CastMacGeneral,
            CKM_CDMF_CBC => MechanismType::CdmfCbc,
            CKM_CDMF_CBC_PAD => MechanismType::CdmfCbcPad,
            CKM_CDMF_ECB => MechanismType::CdmfEcb,
            CKM_CDMF_KEY_GEN => MechanismType::CdmfKeyGen,
            CKM_CDMF_MAC => MechanismType::CdmfMac,
            CKM_CDMF_MAC_GENERAL => MechanismType::CdmfMacGeneral,
            CKM_CMS_SIG => MechanismType::CmsSig,
            CKM_CONCATENATE_BASE_AND_DATA => MechanismType::ConcatenateBaseAndData,
            CKM_CONCATENATE_BASE_AND_KEY => MechanismType::ConcatenateBaseAndKey,
            CKM_CONCATENATE_DATA_AND_BASE => MechanismType::ConcatenateDataAndBase,
            CKM_DES2_KEY_GEN => MechanismType::Des2KeyGen,
            CKM_DES3_KEY_GEN => MechanismType::Des3KeyGen,
            CKM_DES3_ECB => MechanismType::Des3Ecb,
            CKM_DES3_CBC => MechanismType::Des3Cbc,
            CKM_DES3_MAC => MechanismType::Des3Mac,
            CKM_DES3_MAC_GENERAL => MechanismType::Des3MacGeneral,
            CKM_DES3_CBC_PAD => MechanismType::Des3CbcPad,
            CKM_DES3_CMAC_GENERAL => MechanismType::Des3CmacGeneral,
            CKM_DES3_CMAC => MechanismType::Des3Cmac,
            CKM_DES3_ECB_ENCRYPT_DATA => MechanismType::Des3EcbEncryptData,
            CKM_DES3_CBC_ENCRYPT_DATA => MechanismType::Des3CbcEncryptData,
            CKM_DES_CBC => MechanismType::DesCbc,
            CKM_DES_CBC_ENCRYPT_DATA => MechanismType::DesCbcEncryptData,
            CKM_DES_CBC_PAD => MechanismType::DesCbcPad,
            CKM_DES_CFB8 => MechanismType::DesCfb8,
            CKM_DES_CFB64 => MechanismType::DesCfb64,
            CKM_DES_ECB => MechanismType::DesEcb,
            CKM_DES_ECB_ENCRYPT_DATA => MechanismType::DesEcbEncryptData,
            CKM_DES_KEY_GEN => MechanismType::DesKeyGen,
            CKM_DES_MAC => MechanismType::DesMac,
            CKM_DES_MAC_GENERAL => MechanismType::DesMacGeneral,
            CKM_DES_OFB8 => MechanismType::DesOfb8,
            CKM_DES_OFB64 => MechanismType::DesOfb64,
            CKM_DH_PKCS_DERIVE => MechanismType::DhPkcsDerive,
            CKM_DH_PKCS_KEY_PAIR_GEN => MechanismType::DhPkcsKeyPairGen,
            CKM_DH_PKCS_PARAMETER_GEN => MechanismType::DhPkcsParameterGen,
            CKM_DSA => MechanismType::Dsa,
            CKM_DSA_KEY_PAIR_GEN => MechanismType::DsaKeyPairGen,
            CKM_DSA_PARAMETER_GEN => MechanismType::DsaParameterGen,
            CKM_DSA_PROBABLISTIC_PARAMETER_GEN => MechanismType::DsaProbablisticParameterGen,
            CKM_DSA_SHA1 => MechanismType::DsaSha1,
            CKM_DSA_SHA224 => MechanismType::DsaSha224,
            CKM_DSA_SHA256 => MechanismType::DsaSha256,
            CKM_DSA_SHA384 => MechanismType::DsaSha384,
            CKM_DSA_SHA512 => MechanismType::DsaSha512,
            CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN => MechanismType::DsaShaweTaylorParameterGen,
            CKM_ECDH1_DERIVE => MechanismType::Ecdh1Derive,
            CKM_ECDH1_COFACTOR_DERIVE => MechanismType::Ecdh1CofactorDerive,
            CKM_ECDH_AES_KEY_WRAP => MechanismType::EcdhAesKeyWrap,
            CKM_ECDSA => MechanismType::Ecdsa,
            CKM_ECDSA_KEY_PAIR_GEN => MechanismType::EcdsaKeyPairGen,
            CKM_ECDSA_SHA1 => MechanismType::EcdsaSha1,
            CKM_ECDSA_SHA224 => MechanismType::EcdsaSha224,
            CKM_ECDSA_SHA256 => MechanismType::EcdsaSha256,
            CKM_ECDSA_SHA384 => MechanismType::EcdsaSha384,
            CKM_ECDSA_SHA512 => MechanismType::EcdsaSha512,
            CKM_ECMQV_DERIVE => MechanismType::EcmqvDerive,
            CKM_EXTRACT_KEY_FROM_KEY => MechanismType::ExtractKeyFromKey,
            CKM_FASTHASH => MechanismType::Fasthash,
            CKM_FORTEZZA_TIMESTAMP => MechanismType::FortezzaTimestamp,
            CKM_GENERIC_SECRET_KEY_GEN => MechanismType::GenericSecretKeyGen,
            CKM_GOST28147_KEY_GEN => MechanismType::Gost28147KeyGen,
            CKM_GOST28147_ECB => MechanismType::Gost28147Ecb,
            CKM_GOST28147 => MechanismType::Gost28147,
            CKM_GOST28147_MAC => MechanismType::Gost28147Mac,
            CKM_GOST28147_KEY_WRAP => MechanismType::Gost28147KeyWrap,
            CKM_GOSTR3410_KEY_PAIR_GEN => MechanismType::Gostr3410KeyPairGen,
            CKM_GOSTR3410 => MechanismType::Gostr3410,
            CKM_GOSTR3410_KEY_WRAP => MechanismType::Gostr3410KeyWrap,
            CKM_GOSTR3410_DERIVE => MechanismType::Gostr3410Derive,
            CKM_GOSTR3411 => MechanismType::Gostr3411,
            CKM_GOSTR3411_HMAC => MechanismType::Gostr3411Hmac,
            CKM_GOSTR3410_WITH_GOSTR3411 => MechanismType::Gostr3410WithGostr3411,
            CKM_HOTP => MechanismType::Hotp,
            CKM_HOTP_KEY_GEN => MechanismType::HotpKeyGen,
            CKM_IDEA_CBC => MechanismType::IdeaCbc,
            CKM_IDEA_CBC_PAD => MechanismType::IdeaCbcPad,
            CKM_IDEA_ECB => MechanismType::IdeaEcb,
            CKM_IDEA_KEY_GEN => MechanismType::IdeaKeyGen,
            CKM_IDEA_MAC => MechanismType::IdeaMac,
            CKM_IDEA_MAC_GENERAL => MechanismType::IdeaMacGeneral,
            CKM_JUNIPER_CBC128 => MechanismType::JuniperCbc128,
            CKM_JUNIPER_COUNTER => MechanismType::JuniperCounter,
            CKM_JUNIPER_ECB128 => MechanismType::JuniperEcb128,
            CKM_JUNIPER_KEY_GEN => MechanismType::JuniperKeyGen,
            CKM_JUNIPER_SHUFFLE => MechanismType::JuniperShuffle,
            CKM_JUNIPER_WRAP => MechanismType::JuniperWrap,
            CKM_KEA_DERIVE => MechanismType::KeaDerive,
            CKM_KEA_KEY_DERIVE => MechanismType::KeaKeyDerive,
            CKM_KEA_KEY_PAIR_GEN => MechanismType::KeaKeyPairGen,
            CKM_KEY_WRAP_LYNKS => MechanismType::KeyWrapLynks,
            CKM_KEY_WRAP_SET_OAEP => MechanismType::KeyWrapSetOaep,
            CKM_KIP_DERIVE => MechanismType::KipDerive,
            CKM_KIP_MAC => MechanismType::KipMac,
            CKM_KIP_WRAP => MechanismType::KipWrap,
            CKM_MD2_RSA_PKCS => MechanismType::Md2RsaPkcs,
            CKM_MD2 => MechanismType::Md2,
            CKM_MD2_HMAC => MechanismType::Md2Hmac,
            CKM_MD2_HMAC_GENERAL => MechanismType::Md2HmacGeneral,
            CKM_MD2_KEY_DERIVATION => MechanismType::Md2KeyDerivation,
            CKM_MD5_RSA_PKCS => MechanismType::Md5RsaPkcs,
            CKM_MD5 => MechanismType::Md5,
            CKM_MD5_HMAC => MechanismType::Md5Hmac,
            CKM_MD5_HMAC_GENERAL => MechanismType::Md5HmacGeneral,
            CKM_MD5_KEY_DERIVATION => MechanismType::Md5KeyDerivation,
            CKM_PBA_SHA1_WITH_SHA1_HMAC => MechanismType::PbaSha1WithSha1Hmac,
            CKM_PBE_MD2_DES_CBC => MechanismType::PbeMd2DesCbc,
            CKM_PBE_MD5_DES_CBC => MechanismType::PbeMd5DesCbc,
            CKM_PBE_MD5_CAST_CBC => MechanismType::PbeMd5CastCbc,
            CKM_PBE_MD5_CAST3_CBC => MechanismType::PbeMd5Cast3Cbc,
            CKM_PBE_MD5_CAST5_CBC => MechanismType::PbeMd5Cast5Cbc,
            CKM_PBE_SHA1_CAST5_CBC => MechanismType::PbeSha1Cast5Cbc,
            CKM_PBE_SHA1_DES2_EDE_CBC => MechanismType::PbeSha1Des2EdeCbc,
            CKM_PBE_SHA1_DES3_EDE_CBC => MechanismType::PbeSha1Des3EdeCbc,
            CKM_PBE_SHA1_RC2_40_CBC => MechanismType::PbeSha1Rc2_40Cbc,
            CKM_PBE_SHA1_RC2_128_CBC => MechanismType::PbeSha1Rc2_128Cbc,
            CKM_PBE_SHA1_RC4_40 => MechanismType::PbeSha1Rc4_40,
            CKM_PBE_SHA1_RC4_128 => MechanismType::PbeSha1Rc4_128,
            CKM_PKCS5_PBKD2 => MechanismType::Pkcs5Pbkd2,
            CKM_RC2_KEY_GEN => MechanismType::Rc2KeyGen,
            CKM_RC2_ECB => MechanismType::Rc2Ecb,
            CKM_RC2_CBC => MechanismType::Rc2Cbc,
            CKM_RC2_MAC => MechanismType::Rc2Mac,
            CKM_RC2_MAC_GENERAL => MechanismType::Rc2MacGeneral,
            CKM_RC2_CBC_PAD => MechanismType::Rc2CbcPad,
            CKM_RC4_KEY_GEN => MechanismType::Rc4KeyGen,
            CKM_RC4 => MechanismType::Rc4,
            CKM_RC5_KEY_GEN => MechanismType::Rc5KeyGen,
            CKM_RC5_ECB => MechanismType::Rc5Ecb,
            CKM_RC5_CBC => MechanismType::Rc5Cbc,
            CKM_RC5_MAC => MechanismType::Rc5Mac,
            CKM_RC5_MAC_GENERAL => MechanismType::Rc5MacGeneral,
            CKM_RC5_CBC_PAD => MechanismType::Rrc5CbcPad,
            CKM_RIPEMD128_RSA_PKCS => MechanismType::Ripemd128RsaPkcs,
            CKM_RIPEMD128 => MechanismType::Ripemd128,
            CKM_RIPEMD128_HMAC => MechanismType::Ripemd128Hmac,
            CKM_RIPEMD128_HMAC_GENERAL => MechanismType::Ripemd128HmacGeneral,
            CKM_RIPEMD160_RSA_PKCS => MechanismType::Ripemd160RsaPkcs,
            CKM_RIPEMD160 => MechanismType::Ripemd160,
            CKM_RIPEMD160_HMAC => MechanismType::Ripemd160Hmac,
            CKM_RIPEMD160_HMAC_GENERAL => MechanismType::Ripemd160HmacGeneral,
            CKM_RSA_9796 => MechanismType::Rsa9796,
            CKM_RSA_AES_KEY_WRAP => MechanismType::RsaAesKeyWrap,
            CKM_RSA_PKCS => MechanismType::RsaPkcs,
            CKM_RSA_PKCS_KEY_PAIR_GEN => MechanismType::RsaPkcsKeyPairGen,
            CKM_RSA_PKCS_OAEP => MechanismType::RsaPkcsOaep,
            CKM_RSA_PKCS_OAEP_TPM_1_1 => MechanismType::RsaPkcsOaepTpm11,
            CKM_RSA_PKCS_PSS => MechanismType::RsaPkcsPss,
            CKM_RSA_PKCS_TPM_1_1 => MechanismType::RsaPkcsTpm11,
            CKM_RSA_X9_31_KEY_PAIR_GEN => MechanismType::RsaX9_31KeyPairGen,
            CKM_RSA_X9_31 => MechanismType::RsaX9_31,
            CKM_RSA_X_509 => MechanismType::RsaX509,
            CKM_SECURID => MechanismType::Securid,
            CKM_SECURID_KEY_GEN => MechanismType::SecuridKeyGen,
            CKM_SEED_CBC => MechanismType::SeedCbc,
            CKM_SEED_CBC_ENCRYPT_DATA => MechanismType::SeedCbcEncryptData,
            CKM_SEED_CBC_PAD => MechanismType::SeedCbcPad,
            CKM_SEED_ECB => MechanismType::SeedEcb,
            CKM_SEED_ECB_ENCRYPT_DATA => MechanismType::SeedEcbEncryptData,
            CKM_SEED_KEY_GEN => MechanismType::SeedKeyGen,
            CKM_SEED_MAC => MechanismType::SeedMac,
            CKM_SEED_MAC_GENERAL => MechanismType::SeedMacGeneral,
            CKM_SHA1_RSA_PKCS => MechanismType::Sha1RsaPkcs,
            CKM_SHA1_RSA_PKCS_PSS => MechanismType::Sha1RsaPkcsPss,
            CKM_SHA1_KEY_DERIVATION => MechanismType::Sha1KeyDerivation,
            CKM_SHA224_RSA_PKCS => MechanismType::Sha224RsaPkcs,
            CKM_SHA224_RSA_PKCS_PSS => MechanismType::Sha224RsaPkcsPss,
            CKM_SHA224 => MechanismType::Sha224,
            CKM_SHA224_HMAC => MechanismType::Sha224Hmac,
            CKM_SHA224_HMAC_GENERAL => MechanismType::Sha224HmacGeneral,
            CKM_SHA224_KEY_DERIVATION => MechanismType::Sha224KeyDerivation,
            CKM_SHA256_RSA_PKCS => MechanismType::Sha256RsaPkcs,
            CKM_SHA256_RSA_PKCS_PSS => MechanismType::Sha256RsaPkcsPss,
            CKM_SHA256 => MechanismType::Sha256,
            CKM_SHA256_HMAC => MechanismType::Sha256Hmac,
            CKM_SHA256_HMAC_GENERAL => MechanismType::Sha256HmacGeneral,
            CKM_SHA256_KEY_DERIVATION => MechanismType::Sha256KeyDerivation,
            CKM_SHA384_RSA_PKCS => MechanismType::Sha384RsaPkcs,
            CKM_SHA384_RSA_PKCS_PSS => MechanismType::Sha384RsaPkcsPss,
            CKM_SHA384 => MechanismType::Sha384,
            CKM_SHA384_HMAC => MechanismType::Sha384Hmac,
            CKM_SHA384_HMAC_GENERAL => MechanismType::Sha384HmacGeneral,
            CKM_SHA384_KEY_DERIVATION => MechanismType::Sha384KeyDerivation,
            CKM_SHA512_RSA_PKCS => MechanismType::Sha512RsaPkcs,
            CKM_SHA512_RSA_PKCS_PSS => MechanismType::Sha512RsaPkcsPss,
            CKM_SHA512_T => MechanismType::Sha512T,
            CKM_SHA512_T_HMAC => MechanismType::Sha512THmac,
            CKM_SHA512_T_HMAC_GENERAL => MechanismType::Sha512THmacGeneral,
            CKM_SHA512_T_KEY_DERIVATION => MechanismType::Sha512TKeyDerivation,
            CKM_SHA512 => MechanismType::Sha512,
            CKM_SHA512_HMAC => MechanismType::Sha512Hmac,
            CKM_SHA512_HMAC_GENERAL => MechanismType::Sha512HmacGeneral,
            CKM_SHA512_KEY_DERIVATION => MechanismType::Sha512KeyDerivation,
            CKM_SHA1_RSA_X9_31 => MechanismType::Sha1RsaX9_31,
            CKM_SHA512_224 => MechanismType::Sha512_224,
            CKM_SHA512_224_HMAC => MechanismType::Sha512_224Hmac,
            CKM_SHA512_224_HMAC_GENERAL => MechanismType::Sha512_224HmacGeneral,
            CKM_SHA512_224_KEY_DERIVATION => MechanismType::Sha512_224KeyDerivation,
            CKM_SHA512_256 => MechanismType::Sha512_256,
            CKM_SHA512_256_HMAC => MechanismType::Sha512_256Hmac,
            CKM_SHA512_256_HMAC_GENERAL => MechanismType::Sha512_256HmacGeneral,
            CKM_SHA512_256_KEY_DERIVATION => MechanismType::Sha512_256KeyDerivation,
            CKM_SHA_1 => MechanismType::Sha1,
            CKM_SHA_1_HMAC => MechanismType::Sha1Hmac,
            CKM_SHA_1_HMAC_GENERAL => MechanismType::Sha1HmacGeneral,
            CKM_SKIPJACK_CBC64 => MechanismType::SkipjackCbc64,
            CKM_SKIPJACK_CFB8 => MechanismType::SkipjackCfb8,
            CKM_SKIPJACK_CFB16 => MechanismType::SkipjackCfb16,
            CKM_SKIPJACK_CFB32 => MechanismType::SkipjackCfb32,
            CKM_SKIPJACK_CFB64 => MechanismType::SkipjackCfb64,
            CKM_SKIPJACK_ECB64 => MechanismType::SkipjackEcb64,
            CKM_SKIPJACK_KEY_GEN => MechanismType::SkipjackKeyGen,
            CKM_SKIPJACK_OFB64 => MechanismType::SkipjackOfb64,
            CKM_SKIPJACK_PRIVATE_WRAP => MechanismType::SkipjackPrivateWrap,
            CKM_SKIPJACK_RELAYX => MechanismType::SkipjackRelayx,
            CKM_SKIPJACK_WRAP => MechanismType::SkipjackWrap,
            CKM_SSL3_PRE_MASTER_KEY_GEN => MechanismType::Ssl3PreMasterKeyGen,
            CKM_SSL3_MASTER_KEY_DERIVE => MechanismType::Ssl3MasterKeyDerive,
            CKM_SSL3_KEY_AND_MAC_DERIVE => MechanismType::Ssl3KeyAndMacDerive,
            CKM_SSL3_MASTER_KEY_DERIVE_DH => MechanismType::Ssl3MasterKeyDeriveDh,
            CKM_SSL3_MD5_MAC => MechanismType::Ssl3Md5Mac,
            CKM_SSL3_SHA1_MAC => MechanismType::Ssl3Sha1Mac,
            CKM_TLS10_MAC_SERVER => MechanismType::Tls10MacServer,
            CKM_TLS10_MAC_CLIENT => MechanismType::Tls10MacClient,
            CKM_TLS12_MAC => MechanismType::Tls12Mac,
            CKM_TLS12_KDF => MechanismType::Tls12Kdf,
            CKM_TLS12_MASTER_KEY_DERIVE => MechanismType::Tls12MasterKeyDerive,
            CKM_TLS12_KEY_AND_MAC_DERIVE => MechanismType::Tls12KeyAndMacDerive,
            CKM_TLS12_MASTER_KEY_DERIVE_DH => MechanismType::Tls12MasterKeyDeriveDh,
            CKM_TLS12_KEY_SAFE_DERIVE => MechanismType::Tls12KeySafeDerive,
            CKM_TLS_KDF => MechanismType::TlsKdf,
            CKM_TLS_KEY_AND_MAC_DERIVE => MechanismType::TlsKeyAndMacDerive,
            CKM_TLS_MAC => MechanismType::TlsMac,
            CKM_TLS_MASTER_KEY_DERIVE => MechanismType::TlsMasterKeyDerive,
            CKM_TLS_MASTER_KEY_DERIVE_DH => MechanismType::TlsMasterKeyDeriveDh,
            CKM_TLS_PRE_MASTER_KEY_GEN => MechanismType::TlsPreMasterKeyGen,
            CKM_TLS_PRF => MechanismType::TlsPrf,
            CKM_TWOFISH_CBC => MechanismType::TwofishCbc,
            CKM_TWOFISH_CBC_PAD => MechanismType::TwofishCbcPad,
            CKM_TWOFISH_KEY_GEN => MechanismType::TwofishKeyGen,
            CKM_VENDOR_DEFINED => MechanismType::VendorDefined,
            CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE => MechanismType::WtlsClientKeyAndMacDerive,
            CKM_WTLS_MASTER_KEY_DERIVE => MechanismType::WtlsMasterKeyDerive,
            CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC => MechanismType::WtlsMasterKeyDeriveDhEcc,
            CKM_WTLS_PRE_MASTER_KEY_GEN => MechanismType::WtlsPreMasterKeyGen,
            CKM_WTLS_PRF => MechanismType::WtlsPrf,
            CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE => MechanismType::WtlsServerKeyAndMacDerive,
            CKM_X9_42_DH_KEY_PAIR_GEN => MechanismType::X9_42DhKeyPairGen,
            CKM_X9_42_DH_DERIVE => MechanismType::X9_42DhDerive,
            CKM_X9_42_DH_HYBRID_DERIVE => MechanismType::X9_42DhHybridDerive,
            CKM_X9_42_MQV_DERIVE => MechanismType::X9_42MqvDerive,
            CKM_X9_42_DH_PARAMETER_GEN => MechanismType::X9_42DhParameterGen,
            CKM_XOR_BASE_AND_DATA => MechanismType::XorBaseAndData,
            m => panic!("Unknown mechanism type {}", m),
        }
    }
}
